---
apiVersion: v1
kind: Service
metadata:
  name: level-service
spec:
  selector:
    app: level-service
  ports:
    - name: service
      port: 8080
      targetPort: 8080
    - name: management
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment

metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: level-service
  name: level-service
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: level-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: level-service
    spec:
      containers:
        - image: registry.digitalocean.com/pet-project/level-service:latest
          imagePullPolicy: Always
          name: level-service
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

  #helm install mariadb bitnami/mariadb -f values-production.yaml --set rootUser.password=test --set replication.password=test --set db.user=level --set db.password=test --set db.name=level_db